제품상세페이지에 들어갈 order 컴포넌트 구현
bookstore-README/front_bookstore-README pull request #149
Opened 2024-02-06 10:51 UTC by Hongjw030

## 구현사항

제품 상세페이지에 들어갈 order 컴포넌트

1. components/orderNavigator/staticOrderNavigator.tsx : 제품상세페이지 책 정보 옆에 붙어있는 구매하기, 장바구니 버튼 컴포넌트.
2. components/orderNavigator/sideOrderNavigator.tsx : 제품 상세페이지 스크롤을 아래로 내렸을 때 나타나는, 화면 오른쪽 사이드바 장바구니 컴포넌트. 데스크탑 화면에서만 나타남.
3. components/footerNavigator/footerOrderNavigator.tsx : 제품 상세페이지 스크롤을 아래로 내렸을 때 나타나는, 화면 아래 sticky 장바구니 컴포넌트. 모바, 타블렛 화면에서만 나타남.

-[] 구현한 내용 및 설명

## 사용방법

localhost:3000/bookdetail/35 에 들어가면 바로 볼 수 있습니다,

- [ ] -, + 버튼을 눌렀을 때 수량과 총 가격이 잘 바뀌는지? 
- [ ] 데탑 환경에선 스크롤을 내렸을 때 화면 오른쪽에 order 컴포넌트가 잘 보이는지? 
- [ ] 모바, 타블렛 환경에서 스크롤을 내렸을 때 화면 밑에 order 컴포넌트가 sticky 상태로 잘 보이는지? 

## 스크린샷

![image](https://github.com/bookstore-README/front_bookstore-README/assets/89698149/d7d05084-a40c-429f-a3e9-feac39c2789b)

![image](https://github.com/bookstore-README/front_bookstore-README/assets/89698149/3caea4f1-f3ee-4a33-a3db-4b94165e0af7)

![image](https://github.com/bookstore-README/front_bookstore-README/assets/89698149/26ce5241-ea5a-4299-a7d0-ab3418a17349)

![asdfas](https://github.com/bookstore-README/front_bookstore-README/assets/89698149/89cba1a1-be86-4e0a-aeab-094329f7bc12)

##### close #

2024-02-06 12:16 UTC, thisisthewa2 commented
충돌은 프리티어 설정에 따른 정렬 때문인 것 같으니 원래 재원님 코드 유지하시구 로컬에서 저장 한 번만 하면 프리티어 정렬될 겁니다!

2024-02-06 12:29 UTC, thisisthewa2 commented on src/components/card/bookDetailCard/bookDetailCard.tsx
> +      <BookDetailImg imageUrl={Mock.imageUrl} />
독립된 컴포넌트로 뺀 거 좋네요 👍

2024-02-06 12:33 UTC, thisisthewa2 requested changes

2024-02-06 12:33 UTC, thisisthewa2 commented on src/pages/bookdetail/[bookId].tsx
> +      <MainLayout>
헤더를 포함한 메인레이아웃 상위 div에 max-width를 설정하면 1200px 이상일 때 헤더가 잘립니다 ㅠㅠ,, 레이아웃 안에 max-width를 포함시키도록 수정해주시겠어요?

2024-02-06 12:36 UTC, thisisthewa2 approved these changes
고생하셨습니다! 레이아웃 부분만 수정해주심 좋을 것 같아요 😍

2024-02-07 07:08 UTC, hongjw030 commented on src/pages/bookdetail/[bookId].tsx
> +      <MainLayout>
네~!!! 이 부분 바로 수정하겠습니다, 체크 감사합니다!!! u.u

2024-02-07 07:41 UTC, hyejungan approved these changes
👍👍👍 수고하셨습니다

2024-02-07 07:41 UTC, hyejungan commented on src/pages/bookdetail/[bookId].tsx
> +            </div>
👍

2024-02-07 07:44 UTC, merged