로그인하고 책상세페이지 접속 시 조회수 증가 기능 추가
bookstore-README/front_bookstore-README pull request #299
Opened 2024-02-17 12:39 UTC by Hongjw030

## 구현사항

아주 적은 내용이지만.. pr 쪼개기를 위해  u.u

로그인한 후 책 상세페이지에 접속하면 조회수가 증가하는 api를 추가했습니다.
로그인 안 하고 접속하면 조회수가 증가하지 않습니다!!

-[] 구현한 내용 및 설명

## 사용방법

1. 로그인하기 전 일단 swagger에서 책 아무거나 bookId/bookdetail api get 해서 viewCount가 몇인지 확인한다
2. localhost:3000 페이지에서 로그인한 후, 아까전에 vewiCount를 확인했던 책 id로 bookdetail 페이지에 접속한다
3. 다시 swagger을 새로고침한다음 해당 bookId의 bookdetail을 체크하면 viewCount가 1 증가한 것을 확인할 수 있다!!

## 스크린샷

viewCount를 보여주는 ui가 없어서 넘어갑니다.

##### close #

2024-02-17 12:40 UTC, Hongjw030 commented on src/api/book.ts
> +  const result = await instance.put(`/book/${bookId}/view`);
api가 바뀌어서 memberId가 필요없어졌더라구요, 그래서 수정했습니다..!

2024-02-18 01:55 UTC, thisisthewa2 requested changes
저 재원님 어째선지 테스트 방법 그대로 따라 했는데 조회수가 증가되질 않아요ㅠ
혹시나 해서 로그아웃 하고 해봐도 안 되네요, 스웨거도 새로고침했는데 왤까요

2024-02-18 02:00 UTC, Hongjw030 commented
> 저 재원님 어째선지 테스트 방법 그대로 따라 했는데 조회수가 증가되질 않아요ㅠ
> 혹시나 해서 로그아웃 하고 해봐도 안 되네요, 스웨거도 새로고침했는데 왤까요
> 

아...!! 혹시 이전에 접속한적 있는 책 페이지인가요??? 의도된건진 모르겠는데 한번 조회수가 늘어나면 새로고침해도 안 늘어나고 딱 +1만 되더라구요, (무한 조회수증가를 막으려고 그러는듯한??... 
혹시 한번도 접속한적없는 새 책으로 들어가보시겠어요?!?!

2024-02-18 05:20 UTC, thisisthewa2 approved these changes
어푸푸! 고생하셨습니다

2024-02-19 02:52 UTC, orrhrr approved these changes
확인했습니당!!

2024-02-19 05:22 UTC, merged